[project]
name = "minebot"
version = "1.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "aiomysql==0.2.0",
    "aiosqlite==0.21.0",
    "asyncpg==0.30.0",
    "hikari-lightbulb==3.0.0a19",
    "hikari-toolbox==0.1.7",
    "hikari[speedups]==2.3.1",
    "pydantic==2.11.4",
    "pydantic-extra-types==2.10.4",
    "sqlalchemy==2.0.40",
    "websockets==15.0.1",
    "uvloop==0.21.0; sys_platform != 'win32'"
]
